<section class="content-header">
    <h1>

        <small></small>
    </h1>
</section>
<div id="quiz_painel">
<?php
                foreach($quizs as $quiz):
                extract($quiz->toArray()); ?>
                <div class="col-md-4"><div class="info-box">
                        <span class="info-box-icon bg-gree"><i class="fa fa-edit"></i></span>
                        <div class="info-box-content">
                            <span class="info-box-text"><?=$name;?></span>
                            <span class="info-box-number">
                                <div class="margin">
                                    <?php
                                    if($status == 1)
                                      echo  "<a id='$id' data-toggle=\"modal\" data-target=\"#modal-user-information\" type=\"button\" class=\"btn btn-default btn-success btn-block\">Iniciar</a>";
                                    else
                                       echo "<a type=\"button\" class=\"btn btn-default btn-danger btn-block disabled\">Finalizado</a>";
                                    ?>

                                </div>
                            </span>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
</div>
<div id="contentquiz" hidden>

</div>
<!-- MODAL USER INFORMATION ANSWER-->
<div class="modal fade" id="modal-user-information">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Validação</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label>Nome Completo</label>
                        <input type="text" name="name_user" id="name_user" class="form-control" placeholder="Nome completo" required="required" value="">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" name="email" id="email" class="form-control" placeholder="Email" required="required" value="">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<?php
$this->inlineScript()->captureStart();
echo <<<JS
   $(".btn-block").on("click", function(){
       $.ajax({
                type: "POST",
                url:"./painel/getquiz",
                data: { 
                    'quiz_id': $(this).attr('id'), 
                },
                dataType:   'json', 
                async:      true,
                success: function(response) {    
                    
                    ///*
                    if(response){
                        $('#contentquiz').html(response);
                    }
                     else{
                        $("#modal-creat-question .modal-body").html("Error in operation");
                     }//*/
                //$(".modal-body").html(response);
                },
                error: function(jqXHR, textStatus, errorThrown){ 
                   // console.log('my message:' + err); 
                   // $('#result').html('<p>status code: '+jqXHR.status+'</p><p>errorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
                console.log('jqXHR:');
                console.log(jqXHR);
                console.log('textStatus:');
                console.log(textStatus);
                console.log('errorThrown:');
                console.log(errorThrown);
                }
            }); 
   });
    
    

    $(".btn-primary").on("click", function(){
            function validateEmail(email) {
        var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
    return emailReg.test(email);
    }    
            if(!$("#name_user").val()){
                $("#name_user").closest('.form-group').addClass('has-error');
            }
            
            else if(!validateEmail($("#email").val())){
                $("#name_user").closest('.form-group').removeClass('has-error');
                $("#email").closest('.form-group').addClass('has-error');
            }
            else{
                $('#modal-user-information').modal('toggle');
                $('#contentquiz').show();
                $('#quiz_painel').hide();
            }
    });


   
JS;
$this->inlineScript()->captureEnd();
?>