<?= $this->doctype() ?>

<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Quiz')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('css/skin-blue.min.css'))
        ->prependStylesheet($this->basePath('css/dataTables.bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <style>
        .content-wrapper{
            min-height: 873px;padding-left: 16px;padding-right: 15px;padding-top: 15px;
        }
    </style>
</head>
<body class="skin-blue layout-top-nav">

<div class="container">
    <header class="main-header">
        <nav class="navbar navbar-static-top">
            <div class="containers">
                <div class="navbar-header">
                    <a class="navbar-brand"><b>Quiz</b>Dashboard</a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?= $this->url('dashboard')?>">Dashboard</a></li>
                        <li><a href="<?= $this->url('auth')?>">Users</a></li>
                        <?php
                        if(!$this->identity())
                            echo "<li><a href=\"".$this->url('login',['action'=>'login'])."\">Login</a></li>";
                        else
                            echo "<li><a href=\"".$this->url('login',['action'=>'logout'])."\">Logout</a></li>";
                        ?>
                        <li><a title="Responder quiz" href="<?=$this->url('painel');?>"><i class="fa fa-edit"></i></a></li>
                    </ul>
                </div>

            </div>
            <!-- /.container-fluid -->
        </nav>
    </header>
    <div class="content-wrapper" style="min-height: 873px;">
    <?= $this->content ?>
    </div>
    <footer class="main-footer">
        <div class="containers">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.4.7
            </div>
            <strong>Copyright © 2017 Pertencente a <a href="https://ainvengenharia.rf.gd">AINV engenharia LTDA</a>.</strong> All rights
            reserved.
        </div>
        <!-- /.container -->
    </footer>
</div>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/adminlte.min.js'))
    ->prependFile($this->basePath('js/loadingoverlay.min.js'))
    ->prependFile($this->basePath('js/dataTables.bootstrap.min.js'))
    ->prependFile($this->basePath('js/demo.js'))?>
</body>
</html>
