<!--BOX-->
<div class="contents">
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Registereds users</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tr>
                        <th>#</th>
                        <th>login</th>
                        <th>password</th>
                        <th>created at</th>
                        <th>update at</th>
                        <th>status</th>
                        <th>auth</th>
                        <th>actions</th>
                    </tr>
                    <?php
                    foreach($users as $user):
                        extract($user->toArray()); ?>
                        <tr>
                            <td><?=$id;?></td>
                            <td><?=$login;?></td>
                            <td><?=$password;?></td>
                            <td><?=$created;?></td>
                            <td><?=$update;?></td>
                            <td><?=$status;?></td>
                            <td><?=$level;?></td>
                            <td><a class="btn btn-success" href="<?=$this->url('auth',['action' => 'update', 'id'=>$id]);?>">EDITAR</a>
                            <a class="btn btn-danger" href="<?=$this->url('auth',['action' => 'delete', 'id'=>$id]);?>">EXCLUIR</a> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <a class="btn btn-warning" href="<?=$this->url('auth',['action' => 'create']);?>">CREATE</a>
            </div>
        </div>
    </div>
</div>
</div>
        <!--END BOX-->